---

- name: instalar docker y docker-compose Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - docker.io
    - docker-compose
    - python3-pip
  when: ansible_distribution == "Debian"


- name: instalar requirements para modulo docker compose Debian
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
  when: ansible_distribution == "Debian"


- name: instalar docker CentOS
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - docker-ce
  when: ansible_distribution == "CentOS"


- name: Instalar docker-compose CentOS
  shell:
    cmd: curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  when: ansible_distribution == "CentOS"


- name: Dar permisos de ejecucion a docker-compose CentOS
  file:
    path: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0755'
    state: file
  when: ansible_distribution == "CentOS"    


...